/**
 * Drizzle ORM Schema for Auction System
 *
 * Defines the database schema for auctions and bids tables using Drizzle ORM.
 * This replaces manual SQL queries with type-safe database operations.
 *
 * @module auction-dal/db/schema
 */

import {
  pgTable,
  uuid,
  varchar,
  text,
  decimal,
  timestamp,
  integer,
  index,
} from 'drizzle-orm/pg-core';

/**
 * Auctions Table
 *
 * Stores auction listings with pricing, timing, and status information.
 */
export const auctions = pgTable(
  'auctions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').notNull(),
    title: varchar('title', { length: 255 }).notNull(),
    description: text('description'),
    imageUrl: text('image_url'),
    startPrice: decimal('start_price', { precision: 10, scale: 2 }).notNull(),
    reservePrice: decimal('reserve_price', { precision: 10, scale: 2 }),
    currentPrice: decimal('current_price', { precision: 10, scale: 2 }).notNull(),
    startTime: timestamp('start_time', { withTimezone: true }).notNull(),
    endTime: timestamp('end_time', { withTimezone: true }).notNull(),
    status: varchar('status', { length: 20 }).notNull().default('pending'),
    winnerId: uuid('winner_id'),
    bidCount: integer('bid_count').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    // Indexes for common queries
    userIdIdx: index('auctions_user_id_idx').on(table.userId),
    statusIdx: index('auctions_status_idx').on(table.status),
    createdAtIdx: index('auctions_created_at_idx').on(table.createdAt),
  })
);

/**
 * Bids Table
 *
 * Stores bid history for auctions, linked by auction_id foreign key.
 */
export const bids = pgTable(
  'bids',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    auctionId: uuid('auction_id')
      .notNull()
      .references(() => auctions.id, { onDelete: 'cascade' }),
    userId: uuid('user_id').notNull(),
    amount: decimal('amount', { precision: 10, scale: 2 }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    // Indexes for common queries
    auctionIdIdx: index('bids_auction_id_idx').on(table.auctionId),
    userIdIdx: index('bids_user_id_idx').on(table.userId),
    createdAtIdx: index('bids_created_at_idx').on(table.auctionId, table.createdAt),
  })
);

/**
 * TypeScript types inferred from schema
 *
 * These types are automatically generated by Drizzle based on the schema definition.
 */
export type Auction = typeof auctions.$inferSelect;
export type NewAuction = typeof auctions.$inferInsert;
export type Bid = typeof bids.$inferSelect;
export type NewBid = typeof bids.$inferInsert;
