#!/usr/bin/env tsx
/**
 * Drizzle Migration Runner
 *
 * Runs Drizzle migrations to update the database schema.
 * This is the programmatic way to apply migrations generated by `drizzle-kit generate`.
 *
 * Usage: pnpm db:migrate
 */

import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { Pool } from 'pg';

async function runMigrations() {
  console.log('🔄 Running Drizzle migrations...');
  console.log('');

  // Create PostgreSQL connection pool
  const pool = new Pool({
    host: process.env.POSTGRES_HOST || 'localhost',
    port: parseInt(process.env.POSTGRES_PORT || '5432', 10),
    database: process.env.POSTGRES_DB || 'auctions_dev',
    user: process.env.POSTGRES_USER || 'postgres',
    password: process.env.POSTGRES_PASSWORD || 'postgres',
  });

  console.log(`🗄️  Database: ${process.env.POSTGRES_DB || 'auctions_dev'}@${process.env.POSTGRES_HOST || 'localhost'}:${process.env.POSTGRES_PORT || '5432'}`);
  console.log('');

  try {
    const db = drizzle(pool);

    // Run migrations from the drizzle/migrations folder
    await migrate(db, { migrationsFolder: './drizzle/migrations' });

    console.log('✅ Migrations completed successfully!');
    console.log('');
  } catch (error) {
    console.error('❌ Migration failed:');
    console.error(error);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

runMigrations();
